### ISSUE TITLE
Windows/mingw32: Undefined references when upgrading glew 1.13 to 2.0

### ISSUE THREAD

**Issue by adeemij** [nigels-com/glew#139]
First, apologies if this is the wrong place to ask this question.  I have done some searching and checked for common mistakes like incorrect paths, but wasn't able to find this issue.

The basic problem is that I am not able to get my project to link when I swap the 1.13 binaries for the 2.0 binaries.  In more detail:

I have been using the glew 1.13 win32 binaries in my project.  When I swap these out for the 2.0 binaries, the linker fails to find many glew functions:
  undefined reference to `__glewGenVertexArrays'
  undefined reference to `__glewGenBuffers'
  undefined reference to `__glewBindVertexArray'

And so on.  In particular, this list includes glewExperimental, which may not be necessary in 2.0?

I'm using mingw64 to build Win32 binaries on a Windows 7 system.  I've checked the verbose linker output and it does not complain about missing the 2.0 libraries.  My linker options for glew are just:
-lopengl32 -lglew32

I am also compiling with -DGLEW_STATIC.  Other factors of interest are that I'm using the C++11 standard, various SDL2 libraries, and I am building debug-flavor binaries.

I can provide more details or try to split this out into a smaller test case if that is helpful.  I just figured that I'm doing something stupid and someone might be able to point it out.

**Comment by nigels-com** [comment]
I think that for GLEW 2.0 I switched to a newer Dev Studio, with newer compiler and linker.  I could try producing mingw64 binaries from Linux, this sort of issue does crop up from time to time.

**Comment by adeemij** [comment]
An important correction: I am using the classical mingw32, not mingw64.  (I had a lot of issues getting mingw64 to play nicely with all the moving parts when I started this project.)

I've written up a couple small test cases illustrating the issue.  In both cases, using glew 1.13 compiles without issue, while using glew 2.0 introduces problems.

glew_test does not include SDL and does not set up OpenGL, hence at runtime glewInit() will fail.  However, it illustrates the link error of not finding glewExperimental.

glew_sdl_test does include SDL, and illustrates two errors.  First, including glewExperimental causes the same link error.  Not including glewExperimental still causes a runtime error of not finding the glew error reporting function in the glew DLL.

Since mingw32 is losing support in favor of mingw64, I can revisit using that compiler to replicate this issue if you think it might make a difference.

Examples are attached as individual .txt, because github won't accept them otherwise or as a .zip for some reason.

[README.txt](https://github.com/nigels-com/glew/files/888938/README.txt)
[glew_test.h.txt](https://github.com/nigels-com/glew/files/888939/glew_test.h.txt)
[glew_test.cpp.txt](https://github.com/nigels-com/glew/files/888940/glew_test.cpp.txt)
[compile_glew_test.bat.txt](https://github.com/nigels-com/glew/files/888941/compile_glew_test.bat.txt)
[glew_sdl_test.h.txt](https://github.com/nigels-com/glew/files/888942/glew_sdl_test.h.txt)
[glew_sdl_test.cpp.txt](https://github.com/nigels-com/glew/files/888943/glew_sdl_test.cpp.txt)
[compile_glew_sdl_test.bat.txt](https://github.com/nigels-com/glew/files/888944/compile_glew_sdl_test.bat.txt)

**Comment by nigels-com** [comment]
The simplest workaround I can suggest is compiling or linking `glew.c` into your project with `-DGLEW_STATIC` rather than trying to link with the MS toolchain built one.

**Comment by miguelinux** [comment]
Hi @adeemij 

from your file compile_glew_test.bat

```
diff --git a/compile_glew_test.bat.txt b/compile_glew_test.bat.txt
index 00dd63d..a2cf427 100644
--- a/compile_glew_test.bat.txt
+++ b/compile_glew_test.bat.txt
@@ -24,7 +24,7 @@ set DEBUGOPTS=-g -Wall
 set RELEASEOPTS=-Wall
 set CFLAGS=-std=c++11 -DGLEW_STATIC
 set LFLAGS=
-set LIBS=-lmingw32 -mwindows -mconsole -lopengl32 -lglew32
+set LIBS=-lmingw32 -mwindows -mconsole -lglew32 -lopengl32

 REM Include and Library search directories
 set INCDIRS=-I %GLEW_INC%
```

Could you try compiling your example switching the linking order?

**Comment by adeemij** [comment]
@nigels-com I have not tried your approach yet; I am also curious to see what changes occur if I use visual studio, so I'll explore those at the same time.

@miguelinux I get the same link error with either ordering:

```
...\glew_test>g++ -I ../../lib/glew-2.0.0/include/GL -o glew_test.exe -std=c++11 -DGLEW_STATIC -g -Wall glew_test.cpp  -L "F:/dev/mingw32/lib" -L ../../lib/glew-2.0.0/lib/Release/Win32 -lmingw32 -mwindows -mconsole -lglew32 -lopengl32
...\AppData\Local\Temp\cc4sO085.o: In function `Z4Initv':
...\glew_test/glew_test.cpp:7: undefined reference to `glewExperimental'
collect2.exe: error: ld returned 1 exit status
```

Apologies for the delay in response; the usual reasons about life and work and all that apply.

**Comment by miguelinux** [comment]
@adeemij I just re-read your post and I see you are using the binary windows file.

As said @nigels-com, he changed the Windows compiler and it could be the root cause.

I have GLEW working on mingw32, and is working well, but I compile it from sources using mingw32.

I downloaded your files and it compiles in my setup.
Try to compile GLEW from sources, using the sources files (ZIP/TGZ) from http://glew.sourceforge.net/, and use your mingw32 setup.

**Comment by adeemij** [comment]
Just following up here to let you guys know the status.

I ended up living with the older version until recently, when I migrated everything to a clang+mingw-w64+glew-2.1.0 setup (which works well so far).

I suggest closing out this issue as I'm no longer dealing with it, and mingw32 is something of a deprecated compiler these days anyway.  And thanks to everyone who tried to help!
