### ISSUE TITLE
Apple Intel: missing extension glNamedBufferStorageEXT

### ISSUE THREAD

**Issue by Niram7777** [nigels-com/glew#454]
Hello,
I face a missing extension issue. (it was working with 2.2.0)
```
/Users/runner/work/rpcs3/rpcs3/rpcs3/Emu/RSX/GL/glutils/buffer_object.cpp:47:4: error: use of undeclared identifier 'glNamedBufferStorageEXT'; did you mean '__glewBufferStorageEXT'?
   47 |                         DSA_CALL2(NamedBufferStorage, m_id, size, data_, flags);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/rpcs3/rpcs3/rpcs3/Emu/RSX/GL/glutils/common.h:39:3: note: expanded from macro 'DSA_CALL2'
   39 |                 gl##func##EXT(__VA_ARGS__);
      |                 ^~~~~~~~~~~~~
<scratch space>:70:1: note: expanded from here
   70 | glNamedBufferStorageEXT
      | ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/GL/glew.h:24223:43: note: '__glewBufferStorageEXT' declared here
 24223 | GLEW_FUN_EXPORT PFNGLBUFFERSTORAGEEXTPROC __glewBufferStorageEXT;
       |                                           ^
1 error generated.
```
Is it a regression with 2.3.0 or is the extension missing on the Apple Intel platform ?
I would imagine the extension to be in the header glew.h and then eventually filtered out by build flags or at runtime?

**Comment by nigels-com** [comment]
`glNamedBufferStorageEXT` was removed from the upstream extension specification: [KhronosGroup/OpenGL-Registry PR #646](https://github.com/KhronosGroup/OpenGL-Registry/pull/646)

On the face of it, seems reasonable for GLEW to align with the specification.

Question is, is it _useful_ for desktop OpenGL with GL_EXT_direct_state_access support?
GLEW can force it back in again, if it's deemed to be a specification bug, not quite aligned with practices.

**Comment by Niram7777** [comment]
> `glNamedBufferStorageEXT` was removed from the upstream extension specification: [KhronosGroup/OpenGL-Registry PR #646](https://github.com/KhronosGroup/OpenGL-Registry/pull/646)
> 
> On the face of it, seems reasonable for GLEW to align with the specification.
> 
> Question is, is it _useful_ for desktop OpenGL with GL_EXT_direct_state_access support? GLEW can force it back in again, if it's deemed to be a specification bug, not quite aligned with practices.

thanks for the quick investigation.
I understand better with the XML that you mentionned at OpenGL-Registry
I don't know how Glew works but maybe you check at runtime this?
```
            <require comment="Extended by GL_ARB_buffer_storage">
                <command name="glNamedBufferStorageEXT"/>
            </require>
```

(I find https://registry.khronos.org/OpenGL/extensions/EXT/EXT_buffer_storage.txt confusing)

**Comment by Niram7777** [comment]
the issue is still there with your latest PR but I dont have a Mac to debug
we are just going to remove GL for Mac for our emulator
(if I can help , let me know, I let you close the ticket)
